auth-server:
  base-url: http://localhost:8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:0312/springboot
    username: springboot
    password: springboot
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server.base-url}/auth/realms/springboot
        opaquetoken:
          client-id: admin-cli
          client-secret: 87d3ec47-1fcc-47f4-8b8f-7ce2d1c97357

rest:
  services:
    user: ${auth-server.base-url}/auth/admin/realms/springboot/users
    token: ${auth-server.base-url}/auth/realms/springboot/protocol/openid-connect/token

server:
  port: 8081
